web_profiler_wdt:
    resource: '@WebProfilerBundle/Resources/config/routing/wdt.xml'
    prefix: /_wdt

web_profiler_profiler:
    resource: '@WebProfilerBundle/Resources/config/routing/profiler.xml'
    prefix: /_profiler

user_getListUser_test:
    path: /auth/list_user/test/
    controller: App\Controller\UserController::getListUser

user_getDataUser_test:
    path: /auth/get_data_user/test/{id}
    controller: App\Controller\UserController::getDataUser
    requirements:
        id: '\d+'
